In [1]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original 3x3 Array:\n", array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T
print("\nTransposed Array (Rows and Columns Interchanged):\n", transposed_array)


Original 3x3 Array:
 [[ 6 63 96]
 [21 78 33]
 [97 34 22]]

Transposed Array (Rows and Columns Interchanged):
 [[ 6 21 97]
 [63 78 34]
 [96 33 22]]


In [2]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


# Generate a 1D array with 10 elements
array_1d = np.arange(10)
print("1D Array:\n", array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", array_5x2)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
#3Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Add a border of zeros around it (resulting in a 6x6 array)
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:\n", array_with_border)


Original 4x4 Array:
 [[0.73060371 0.95486006 0.75597915 0.62703783]
 [0.92546051 0.76188908 0.59166613 0.40862315]
 [0.17893902 0.6793795  0.61804089 0.31591196]
 [0.58139574 0.82043387 0.48382327 0.84067628]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.73060371 0.95486006 0.75597915 0.62703783 0.        ]
 [0.         0.92546051 0.76188908 0.59166613 0.40862315 0.        ]
 [0.         0.17893902 0.6793795  0.61804089 0.31591196 0.        ]
 [0.         0.58139574 0.82043387 0.48382327 0.84067628 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
#4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.


# Create an array from 10 to 60 with a step of 5
array_step = np.arange(10, 65, 5)
print("Array from 10 to 60 with a step of 5:\n", array_step)


Array from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [5]:
'''5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

'''


# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array_strings)
lowercase = np.char.lower(array_strings)
title_case = np.char.title(array_strings)

print("Original Array:", array_strings)
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", title_case)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [6]:
'''6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
'''

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word
spaced_words = np.array([np.char.join(' ', word) for word in words_array])
print("Array with Spaces Between Characters:\n", spaced_words)


Array with Spaces Between Characters:
 ['h e l l o' 'w o r l d' 'n u m p y']


In [7]:
'''7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
'''

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Extract its diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [9]:
'''9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.'''

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers:\n", random_integers)

# Filter out prime numbers
prime_numbers = np.array([num for num in random_integers if is_prime(num)])
print("\nPrime Numbers in the Array:\n", prime_numbers)


Random Integers:
 [445 163 573 351 751 239 947 258 436 146 372 529 284 455 480 961 764 299
 723 608 684 429 172  64 177 733 402 106 253 675 467 335 982 776 846 886
   2 503  68 314 361 751 608 586  14 553 686 230 304 788 741 801 432 928
  16 125 233 596  15 130 281 567 237 298  61  91 794 945 857  48 628 696
 441 269 114 257 246 764 602 352 227 900 288 882 428 451 151 292  89 884
 354 858 398 807 422 962 965 626 383 781]

Prime Numbers in the Array:
 [163 751 239 947 733 467   2 503 751 233 281  61 857 269 257 227 151  89
 383]


In [12]:
'''
10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages'''

import numpy as np

# Create an array representing daily temperatures for a 30-day month
daily_temperatures = np.random.randint(20, 40, size=30)
print("Daily Temperatures:\n", daily_temperatures)

# Reshape to (5 weeks x 6 days) and calculate weekly averages
weekly_averages = daily_temperatures.reshape(5, 6).mean(axis=1)
print("\nWeekly Averages (5 weeks x 6 days):\n", weekly_averages)


Daily Temperatures:
 [36 22 23 32 36 33 30 39 39 33 32 31 21 22 24 30 24 30 34 33 24 25 27 38
 28 37 35 35 34 33]

Weekly Averages (5 weeks x 6 days):
 [30.33333333 34.         25.16666667 30.16666667 33.66666667]
